### PR TITLE
Congress landing

### PR DESCRIPTION
**Pull request by asadovka**
[Sources](https://github.com/cybercongress/cyberdesign/tree/design-congress_130/congress/landing/.exportedArtboards/landing_congresss)

### CODE REVIEW

**Review by SaveTheAles — COMMENTED** [review]
I believe it will better if we add fork button and fork count on desktop version. 
Also it's too large pics of teammates in mobile version in my opinion. I see this section more portable.

**Comment by asadovka** [comment]
@SaveTheAles ok

**Comment by asadovka** [comment]
@SaveTheAles versions are updated

**Review by mastercyb — APPROVED** [review]

**Comment by SaveTheAles** [comment]
@xhipster @asadovka 
Perfect. I just want to discuss few moments. 
1. We refused to add social media icons on a footer. Is it good idea for now? We have just 1 link from this landing to our GitHub. I propose to add Steemit Reddit Twitter and Telegram channel to footer. 

2. License. In my first review I didn't see missing license, but I think it necessary like our position.

**Comment by xhipster** [comment]
1. It's perfect at the moment. We don't have active communities, hence wait a bit. 
2. Do what the fuck you want is a cool license. 

Ps. I would like to have a blog on congress' site, but not as link, but as standalone blog with rss feed.

**Pull request merged**
